---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackit-compute-operator-manager-role
rules:
- apiGroups:
  - compute.sostackit.dev
  resources:
  - clusters
  - networks
  - servers
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.sostackit.dev
  resources:
  - clusters/finalizers
  - networks/finalizers
  - servers/finalizers
  - volumes/finalizers
  verbs:
  - update
- apiGroups:
  - compute.sostackit.dev
  resources:
  - clusters/status
  - networks/status
  - servers/status
  - volumes/status
  verbs:
  - get
  - patch
  - update
